# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNPushNotification' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNPushNotification
  	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Firestore'
	pod 'Firebase/Messaging'
    	pod 'Firebase/Auth'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'RNPushNotificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNPushNotification-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNPushNotification-tvOS

  target 'RNPushNotification-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
